=== rufae/Lenguaje_Marcas/EP2T_2_RCB/Schema_receta.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="restriccion">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="30"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="recipe">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" type="xs:string"/>
                <xs:element name="recipeinfo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="blurb" type="xs:string"/>
                            <xs:element name="author" type="xs:string"/>
                            <xs:element name="yield" type="xs:string"/>
                            <xs:element name="preptime">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="restriccion">
                                            <xs:attribute name="tmag"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="ingredientlist">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ingredient" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="quantity" type="xs:string"/>
                                        <xs:element name="unit" type="xs:string" minOccurs="0"/>
                                        <xs:element name="fooditem" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="preparation">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="dific">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="easy"/>
                                            <xs:enumeration value="medium"/>
                                            <xs:enumeration value="hard"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>

                <xs:element name="serving" type="xs:string"/>

                <xs:element name="notes">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="25"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

            </xs:sequence>

            <xs:attribute name="num" type="xs:integer" use="required"/>

        </xs:complexType>
    </xs:element>


</xs:schema>

=== rufae/Lenguaje_Marcas/EP2T_2_RCB/Receta.xml
<?xml version="1.0" encoding="UTF-8"?>
<recipe num="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Schema_receta.xsd">
    <title>Hippie Pancakes</title>
    <recipeinfo>
        <blurb>Socially conscious breakfast food</blurb>
        <author>David Horton</author>
        <yield>12 to 16 small pancakes, enough for two hippies</yield>
        <preptime tmag="minutes">10</preptime>
    </recipeinfo>
    <ingredientlist>
        <ingredient>
            <quantity>1</quantity>
            <unit>C</unit>
            <fooditem>unbleached wheat blend flour</fooditem>
        </ingredient>
        <ingredient>
            <quantity>2</quantity>
            <unit>tsp</unit>
            <fooditem>baking powder</fooditem>
        </ingredient>
        <ingredient>
            <quantity>1</quantity>
            <unit>tsp.</unit>
            <fooditem>unrefined sugar</fooditem>
        </ingredient>
        <ingredient>
            <quantity>1</quantity>
            <fooditem>free-range egg</fooditem>
        </ingredient>
        <ingredient>
            <quantity>1 1/4</quantity>
            <unit>C</unit>
            <fooditem>hormone-free milk</fooditem>
        </ingredient>
        <ingredient>
            <quantity>1</quantity><unit>tsp</unit>
            <fooditem>organic vegetable oil</fooditem>
        </ingredient>
    </ingredientlist>
    <preparation dific="easy">Pre-heat griddle over medium heat. Combine dry ingredients in a mixing bowl.
            Stir in egg, milk and oil."
    </preparation>
    <serving>Top with fruit and berries or serve with traditional maple syrup.</serving>
    <notes>All-purpose flour may be used instead of wheat blend, but decrease
    the milk by 1/4 C and cut the baking powder by 1/2 tsp. </notes>
</recipe>
